name: Data Pipeline

on:
  workflow_dispatch: # Allows manual triggering from GitHub UI
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6' # Use the version compatible with your code

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python your_data_pipeline_script.py

      - name: Commit and push CSV files
        if: success()
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          timestamp=$(date +'%Y-%m-%d %H:%M:%S')
          git commit -m "Update CSV files - $timestamp" || echo "No changes to commit"
          git push
